# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=150)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_ContactNumber', message='Not valid formate', regex='07(0|1|2|5|6|7|8)\\d{6}')])),
            ],
        ),
    ]
