# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Location', models.SmallIntegerField(choices=[(0, 'Knet'), (1, 'Balkantel'), (2, 'Customer')])),
                ('URL', models.URLField()),
                ('Type', models.SmallIntegerField(choices=[(0, 'VM'), (1, 'Customer'), (2, 'LXC')])),
            ],
        ),
    ]
