# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datacenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_Domain', message='Not valid format', regex='^[a-z0-9]+(\\.[a-z0-9]+)+$')])),
                ('URL', models.URLField()),
                ('InternalIP', models.GenericIPAddressField()),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('VPNPort', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='ContactNumber',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_ContactNumber', message='Not valid format', regex='07(0|1|2|5|6|7|8)\\d{6}')]),
        ),
        migrations.AddField(
            model_name='vamaster',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company'),
        ),
        migrations.AddField(
            model_name='vamaster',
            name='DataCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DataCenter'),
        ),
    ]
