# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170619_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vamaster',
            name='Company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company'),
        ),
    ]
