# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170619_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='vamaster',
            name='Password',
        ),
        migrations.AlterField(
            model_name='vamaster',
            name='DataCenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DataCenter'),
        ),
    ]
