# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170627_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vamaster',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company'),
        ),
    ]
