# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170627_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='vamaster',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
