# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=150)),
                ('ContactPerson', models.CharField(max_length=100)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_ContactNumber', message='Not valid format', regex='07(0|1|2|5|6|7|8)\\d{6}')])),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Location', models.SmallIntegerField(choices=[(0, 'Knet'), (1, 'Balkantel'), (2, 'Customer')])),
                ('URL', models.URLField()),
                ('Type', models.SmallIntegerField(choices=[(0, 'VM'), (1, 'Customer'), (2, 'LXC')])),
            ],
        ),
        migrations.CreateModel(
            name='VAMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_Domain', message='Not valid format', regex='^[a-z0-9]+(\\.[a-z0-9]+)+$')])),
                ('URL', models.URLField()),
                ('InternalIP', models.GenericIPAddressField()),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('VPNPort', models.IntegerField()),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company')),
                ('DataCenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DataCenter')),
            ],
        ),
    ]
