# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vamaster',
            name='Password',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
