# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170720_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='Location',
            field=models.CharField(choices=[('Knet', 'Knet'), ('Balkantel', 'Balkantel'), ('Customer', 'Customer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='Type',
            field=models.CharField(choices=[('VM', 'VM'), ('Customer', 'Customer'), ('LXC', 'LXC')], max_length=30),
        ),
    ]
