# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170804_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=300)),
                ('PublicKey', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.PublicKey')),
            ],
        ),
    ]
