# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publickey_userva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UserVA')),
            ],
        ),
    ]
