# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=400)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.UserVA')),
            ],
        ),
        migrations.RemoveField(
            model_name='vamaster',
            name='Password',
        ),
        migrations.AddField(
            model_name='privileges',
            name='VAMaster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.VAMaster'),
        ),
    ]
